/*
* Kalkulator Spedytora powstał w celu kalkulacji rentowności przewozów zagranicznych.  

* KalkulatorSpedytora
* Copyright © 2019. 
* Orsulit sp. z o.o.
* NIP: 5272807305
* All rights reserved.

* This End-User License Agreement ("EULA") is a legal agreement between you (either an individual or a single entity) and the mentioned owner of this Software for the software product identified above ("SOFTWARE PRODUCT"). By installing, copying, or otherwise using the SOFTWARE PRODUCT, you agree to be bound by the terms of this EULA. If you do not agree to the terms of this EULA, do not install or use the SOFTWARE PRODUCT.

* SOFTWARE PRODUCT LICENSE
* The SOFTWARE PRODUCT is protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties. The SOFTWARE PRODUCT is licensed, not sold.

* 1. The SOFTWARE PRODUCT is payware. You are expressly prohibited from modifying, merging, selling, or leasing in any matter, the SOFTWARE PRODUCT or any portion thereof

* 2. GRANT OF LICENSE. This EULA grants you the following rights: Installation and Use. You may install and use an only one of copies of the SOFTWARE PRODUCT.

* Distribution. You can’t distribute copies of the SOFTWARE PRODUCT.

* 3. DESCRIPTION OF OTHER RIGHTS AND LIMITATIONS.

* Limitations on Reverse Engineering, Decompilation, and Disassembly. You may not reverse engineer, decompile, or disassemble the SOFTWARE PRODUCT, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.

* Separation of Components.
* The SOFTWARE PRODUCT is licensed as a single product. Its component parts may not be separated for use on more than one computer.

* Software Transfer.
* You may permanently transfer all of your rights under this EULA, provided the recipient agrees to the terms of this EULA.

* Termination.
* Without prejudice to any other rights, the owner of this Software may terminate this EULA if you fail to comply with the terms and conditions of this EULA. In such event, you must destroy all copies of the SOFTWARE PRODUCT and all of its component parts. 

* 4. COPYRIGHT.
* All title and copyrights in and to the SOFTWARE PRODUCT(including but not limited to any images, photographs, animations, video, audio, music, text, and "applets" incorporated into the SOFTWARE PRODUCT), the accompanying printed materials, and any copies of the SOFTWARE PRODUCT are owned by the owner of this Software. The SOFTWARE PRODUCT is protected by copyright laws and international treaty provisions. Therefore, you must treat the SOFTWARE PRODUCT like any other copyrighted material except that you may install the SOFTWARE PRODUCT on a single computer provided you keep the original solely for backup or archival purposes.

* LIMITED WARRANTY

* NO WARRANTIES.
* The owner of this Software expressly disclaims any warranty for the SOFTWARE PRODUCT. The SOFTWARE PRODUCT and any related documentation is provided "as is" without warranty of any kind, either express or implied, including, without limitation, the implied warranties or merchantability, fitness for a particular purpose, or noninfringement. The entire risk arising out of use or performance of the SOFTWARE PRODUCT remains with you.

* NO LIABILITY FOR DAMAGES.
* In no event shall the owner of this Software be liable for any damages whatsoever (including, without limitation, damages for loss of business profits, business interruption, loss of business information, or any other pecuniary loss) arising out of the use of or inability to use this product, even if the owner of this Software has been advised of the possibility of such damages. Because some states/jurisdictions do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you.

*/

package kalkulator.kalkulatorspedytora;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Properties;

/**
 * @author Maciej Skórski
 * Copyright © 2019 Orsulit | Wykonanie: Orsulit sp. z o.o. NIP: 5272807305
 */

public class Wlasciwosci extends javax.swing.JFrame {

    /**
     * Creates new form Wlasciwosci
     */
    public Wlasciwosci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WlasciwosciPanel = new javax.swing.JPanel();
        WlaciwosciText = new javax.swing.JLabel();
        Tekst1_1 = new javax.swing.JLabel();
        Pole1_1 = new javax.swing.JTextField();
        Tekst2_1 = new javax.swing.JLabel();
        Pole2_1 = new javax.swing.JTextField();
        Tekst3_1 = new javax.swing.JLabel();
        Pole3_1 = new javax.swing.JTextField();
        Tekst5_1 = new javax.swing.JLabel();
        Pole4_1 = new javax.swing.JTextField();
        Tekst4_1 = new javax.swing.JLabel();
        Pole5_1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        KomTekst1_1 = new javax.swing.JLabel();
        KomTekst2_1 = new javax.swing.JLabel();
        KomTekst3_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WlasciwosciPanel.setBackground(new java.awt.Color(1, 11, 20));
        WlasciwosciPanel.setForeground(new java.awt.Color(1, 14, 27));
        WlasciwosciPanel.setPreferredSize(new java.awt.Dimension(470, 493));

        WlaciwosciText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WlaciwosciText.setForeground(new java.awt.Color(255, 255, 255));
        WlaciwosciText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WlaciwosciText.setText("Ustawienia:");
        WlaciwosciText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Tekst1_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tekst1_1.setForeground(new java.awt.Color(255, 255, 255));
        Tekst1_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tekst1_1.setText("Stawka/KM:");

        Pole1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pole1_1ActionPerformed(evt);
            }
        });
        Pole1_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Pole1_1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Pole1_1KeyTyped(evt);
            }
        });

        Tekst2_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tekst2_1.setForeground(new java.awt.Color(255, 255, 255));
        Tekst2_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tekst2_1.setText("Stawka VAT:");

        Pole2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pole2_1ActionPerformed(evt);
            }
        });
        Pole2_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Pole2_1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Pole2_1KeyTyped(evt);
            }
        });

        Tekst3_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tekst3_1.setForeground(new java.awt.Color(255, 255, 255));
        Tekst3_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tekst3_1.setText("Minimalna marża:");

        Pole3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pole3_1ActionPerformed(evt);
            }
        });
        Pole3_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Pole3_1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Pole3_1KeyTyped(evt);
            }
        });

        Tekst5_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tekst5_1.setForeground(new java.awt.Color(255, 255, 255));
        Tekst5_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tekst5_1.setText("Decyzja pozytywna:");

        Pole4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pole4_1ActionPerformed(evt);
            }
        });

        Tekst4_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tekst4_1.setForeground(new java.awt.Color(255, 255, 255));
        Tekst4_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tekst4_1.setText("Decyzja negatywna:");

        Pole5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pole5_1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 10, 10));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Załaduj ustawienia");
        jButton2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jButton2HierarchyChanged(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 10, 10));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Zapisz zmiany");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        KomTekst1_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        KomTekst1_1.setForeground(new java.awt.Color(153, 0, 0));
        KomTekst1_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        KomTekst2_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        KomTekst2_1.setForeground(new java.awt.Color(153, 0, 0));
        KomTekst2_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        KomTekst2_1.setText(" ");

        KomTekst3_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        KomTekst3_1.setForeground(new java.awt.Color(153, 0, 0));
        KomTekst3_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        KomTekst3_1.setText(" ");

        javax.swing.GroupLayout WlasciwosciPanelLayout = new javax.swing.GroupLayout(WlasciwosciPanel);
        WlasciwosciPanel.setLayout(WlasciwosciPanelLayout);
        WlasciwosciPanelLayout.setHorizontalGroup(
            WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WlasciwosciPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(WlaciwosciText, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(KomTekst1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KomTekst2_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KomTekst3_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                        .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                                .addComponent(Tekst1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pole1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                                .addComponent(Tekst2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Pole2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                                .addComponent(Tekst3_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pole3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                        .addComponent(Tekst5_1)
                        .addGap(29, 29, 29)
                        .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WlasciwosciPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Pole4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                        .addComponent(Tekst4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pole5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        WlasciwosciPanelLayout.setVerticalGroup(
            WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WlaciwosciText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tekst1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pole1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(KomTekst1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tekst2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pole2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(KomTekst2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tekst3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pole3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KomTekst3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Tekst5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WlasciwosciPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Pole4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tekst4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pole5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(WlasciwosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WlasciwosciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WlasciwosciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pole1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pole1_1ActionPerformed

    }//GEN-LAST:event_Pole1_1ActionPerformed

    private void Pole1_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pole1_1KeyReleased

        KomTekst1_1.setText("");
    }//GEN-LAST:event_Pole1_1KeyReleased

    private void Pole1_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pole1_1KeyTyped

        // Stawka za km jazdy dla podwykonawcy - pole numeryczne po przecinku (do wpisania)
        char liczby = evt.getKeyChar();
        if (Character.isLetter(liczby)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_Pole1_1KeyTyped

    private void Pole2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pole2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pole2_1ActionPerformed

    private void Pole2_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pole2_1KeyReleased

        KomTekst2_1.setText("");
    }//GEN-LAST:event_Pole2_1KeyReleased

    private void Pole2_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pole2_1KeyTyped

        // Stawka za km jazdy dla podwykonawcy - pole numeryczne po przecinku (do wpisania)
        char liczby = evt.getKeyChar();
        if (Character.isLetter(liczby)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_Pole2_1KeyTyped

    private void Pole3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pole3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pole3_1ActionPerformed

    private void Pole3_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pole3_1KeyReleased

        KomTekst3_1.setText("");
    }//GEN-LAST:event_Pole3_1KeyReleased

    private void Pole3_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pole3_1KeyTyped

        // Stawka za km jazdy dla podwykonawcy - pole numeryczne po przecinku (do wpisania)
        char liczby = evt.getKeyChar();
        if (Character.isLetter(liczby)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_Pole3_1KeyTyped

    private void Pole4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pole4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pole4_1ActionPerformed

    private void Pole5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pole5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pole5_1ActionPerformed

    private void jButton2HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jButton2HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2HierarchyChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try (InputStream input = new FileInputStream("ustawienia.properties")) {

            Properties prop = new Properties();

            // load a properties file
            prop.load(input);

            //ustawia zmienione wartosci properties

            String StKM = prop.getProperty("StawkaKM");
            String StVAT = prop.getProperty("StawkaVAT");
            String MinMar = prop.getProperty("MinimalnaMarza");
            String DecPoz = prop.getProperty("DecyzjaPozytywna");
            String DecNeg = prop.getProperty("DecyzjaNegatywna");

            Pole1_1.setText(StKM);
            Pole2_1.setText(StVAT);
            Pole3_1.setText(MinMar);
            Pole4_1.setText(DecPoz);
            Pole5_1.setText(DecNeg);

        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(Pole1_1.getText().trim().isEmpty() && Pole2_1.getText().trim().isEmpty() && Pole3_1.getText().trim().isEmpty())
        {
            KomTekst1_1.setText("Uzupełnij pole Stawka/KM!");
            KomTekst2_1.setText("Uzupełnij pole Stawka VAT!");
            KomTekst3_1.setText("Uzupełnij pole Minimalna marża!");
        }
        else if (Pole1_1.getText().trim().isEmpty())
        {
            KomTekst1_1.setText("Uzupełnij pole Stawka/KM!");
        }
        else if (Pole2_1.getText().trim().isEmpty())
        {
            KomTekst2_1.setText("Uzupełnij pole Stawka VAT!");
        }
        else if (Pole3_1.getText().trim().isEmpty())
        {
            KomTekst3_1.setText("Uzupełnij pole Minimalna marża!");
        }
        else

        try (OutputStream output = new FileOutputStream("ustawienia.properties")) {

            Properties prop = new Properties();

            //JTextField zamiana na stringi

            String StKM = Pole1_1.getText();
            String StVAT = Pole2_1.getText();
            String MinMar = Pole3_1.getText();
            String DecPoz = Pole4_1.getText();
            String DecNeg = Pole5_1.getText();

            // set the properties value
            prop.setProperty("StawkaKM",StKM);
            prop.setProperty("StawkaVAT", StVAT);
            prop.setProperty("MinimalnaMarza", MinMar);
            prop.setProperty("DecyzjaPozytywna", DecPoz);
            prop.setProperty("DecyzjaNegatywna", DecNeg);

            // save properties to project root folder
            prop.store(output, null);

            System.out.println(prop);

        } catch (IOException io) {
            io.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wlasciwosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wlasciwosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wlasciwosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wlasciwosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wlasciwosci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel KomTekst1_1;
    public static javax.swing.JLabel KomTekst2_1;
    public static javax.swing.JLabel KomTekst3_1;
    public static javax.swing.JTextField Pole1_1;
    public static javax.swing.JTextField Pole2_1;
    public static javax.swing.JTextField Pole3_1;
    public static javax.swing.JTextField Pole4_1;
    public static javax.swing.JTextField Pole5_1;
    private javax.swing.JLabel Tekst1_1;
    private javax.swing.JLabel Tekst2_1;
    private javax.swing.JLabel Tekst3_1;
    private javax.swing.JLabel Tekst4_1;
    private javax.swing.JLabel Tekst5_1;
    private javax.swing.JLabel WlaciwosciText;
    private javax.swing.JPanel WlasciwosciPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
